// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id              string `json:"id"`
	TelephoneNumber string `json:"telephone_number"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	Status          int8   `json:"status"`
	Avatar          string `json:"avatar"`
	Data            string `json:"data"`
}

type RegisterReq struct {
	TelephoneNumber string `json:"telephone_number"`
	Password        string `json:"password"`
}

type RegisterResp struct {
	AccessToken string `json:"accessToken"`
}

type LoginReq struct {
	TelephoneNumber string `json:"telephone_number"`
	Password        string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}
